version: '2'

services:
  postgres:
    image: bitnami/postgresql:12
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRESQL_DATABASE: CPG
      POSTGRESQL_USERNAME: cpg_ml
      POSTGRESQL_PASSWORD: codepropertygraph
      MAX_CONNECTIONS: 500
    ports:
      - 127.0.0.1:5432:5432
  neo4j:
    image: docker.io/bitnami/neo4j:4
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./feature_generation/csvfiles:/bitnami/neo4j/import
volumes:
  pgdata:
  neo4j_data:

